### ISSUE TITLE
Trying to run /pc on Bungee 1.15.2 causes this exception

### ISSUE THREAD

**Issue by alexis-evelyn** [JavaFactoryDev/PunishControl-Wiki#16]
https://hastebin.com/gugafusosi.md

Edit: This is 1.3

```
[15:36:27 ERROR] [PunishControl]: [ACF] Caused by: java.lang.IndexOutOfBoundsException: Index 1 out of bounds for length 0
[15:36:27 ERROR] [PunishControl]: [ACF]         at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
[15:36:27 ERROR] [PunishControl]: [ACF]         at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
[15:36:27 ERROR] [PunishControl]: [ACF]         at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
[15:36:27 ERROR] [PunishControl]: [ACF]         at java.base/java.util.Objects.checkIndex(Objects.java:372)
[15:36:27 ERROR] [PunishControl]: [ACF]         at java.base/java.util.ArrayList.get(ArrayList.java:458)
[15:36:27 ERROR] [PunishControl]: [ACF]         at de.leonhard.punishcontrol.goto. .fp.<init>(SourceFile:75)
[15:36:27 ERROR] [PunishControl]: [ACF]         at de.leonhard.punishcontrol.goto. .fe.const(SourceFile:36)
```

**Comment by alexis-evelyn** [comment]
All subcommands appear to be broken too. Running /pc info ign causes everyone a force disconnect.

**Comment by alexis-evelyn** [comment]
It appears that it maybe because of nms. Can you try using https://www.spigotmc.org/resources/protocolize-protocollib-for-bungeecord-waterfall.63778/ as an alternative to encoding the packets yourself?

**Comment by JavaFactoryDev** [comment]
Hi,
it seems like this is caused by the background library used by PunishControlPro which is eol for a long time. I will need to recode it when I have the time to do so.

I am sorry for that.

I hope it will get resolved soon:)
